export default [{
  name: 'Iron',
  key: 'iron',
  image: './Emblem_Iron.png'
}, {
  name: 'Bronze',
  key: 'bronze',
  image: './Emblem_Bronze.png'
}, {
  name: 'Silver',
  key: 'silver',
  image: './Emblem_Silver.png'
}, {
  name: 'Gold',
  key: 'gold',
  image: './Emblem_Gold.png'
}, {
  name: 'Platinum',
  key: 'platinum',
  image: './Emblem_Platinum.png'
}, {
  name: 'Diamond',
  key: 'diamond',
  image: './Emblem_Diamond.png'
}, {
  name: 'Master',
  key: 'master',
  image: './Emblem_Master.png'
}, {
  name: 'Grandmaster',
  key: 'grandmaster',
  image: './Emblem_Grandmaster.png'
}, {
  name: 'Challenger',
  key: 'challenger',
  image: './Emblem_Challenger.png'
}]